import { PROMPTS } from "@/data/prompts";
import { CATEGORIES } from "@/data/categories";
import { Prompt, PromptFilterOptions, AIModelId } from "@/types";
import { scorePrompt } from "@/lib/search";

// Category lookup map for fast resolution
const categoryMap = new Map(CATEGORIES.map((c) => [c.slug, c.name]));

function getDefaultTips(prompt: Prompt): string[] {
  const cat = prompt.category.toLowerCase();
  if (
    cat.includes("code") ||
    cat.includes("react") ||
    cat.includes("javascript") ||
    cat.includes("nextjs") ||
    cat.includes("system-design") ||
    cat.includes("developer")
  ) {
    return [
      "Specify your exact runtime and dependency versions (e.g. Next.js 15, React 19, TypeScript 5.4) to eliminate outdated syntax hallucinations.",
      "Ask the model to enumerate potential runtime failure modes, concurrency issues, or null boundary states before generating code.",
      "Request idiomatic, type-safe solutions with clear unit test skeletons rather than monolithic scripts.",
    ];
  }
  if (
    cat.includes("career") ||
    cat.includes("resume") ||
    cat.includes("job-interview") ||
    cat.includes("interview")
  ) {
    return [
      "Anchor your inputs with concrete metrics (revenue influenced, latency reduced, team size) rather than generic qualitative claims.",
      "Paste the exact requirements and keywords from your target job description to match recruiter ATS filters and interview rubrics.",
      "Ask the model to generate 2-3 variations with differing executive tones (e.g., visionary leader vs. hands-on technical operator).",
    ];
  }
  if (
    cat.includes("marketing") ||
    cat.includes("sales") ||
    cat.includes("seo") ||
    cat.includes("business") ||
    cat.includes("copywriting")
  ) {
    return [
      "Explicitly define your Ideal Customer Profile (ICP), their acute pain points, and current legacy alternatives.",
      "Provide strict negative constraints: list corporate clichés, overused jargon, or vague promises the model must avoid.",
      "Ask the model to critique its own copy from the perspective of a cynical, time-pressed prospect before finalizing.",
    ];
  }
  if (
    cat.includes("writing") ||
    cat.includes("content") ||
    cat.includes("email") ||
    cat.includes("creative")
  ) {
    return [
      "Provide a sample paragraph demonstrating your preferred rhythm, cadence, and sentence length.",
      "Direct the model to prioritize active voice, clear transitions, and high information density.",
      "Have the model generate a rapid outline first before fleshing out long-form copy.",
    ];
  }
  return [
    "Provide rich background context rather than one-sentence inputs to receive deep, non-generic responses.",
    "Engage in multi-turn conversation: use the initial output as a baseline, then ask the AI to sharpen specific sections.",
    "Prompt the model to highlight any hidden assumptions or missing trade-offs in its recommendations.",
  ];
}

function getDefaultMistakes(prompt: Prompt): string[] {
  const cat = prompt.category.toLowerCase();
  if (
    cat.includes("code") ||
    cat.includes("react") ||
    cat.includes("javascript") ||
    cat.includes("nextjs") ||
    cat.includes("system-design") ||
    cat.includes("developer")
  ) {
    return [
      "Pasting large unformatted code dumps without indicating the specific function or error you want analyzed.",
      "Deploying AI-generated code directly to production without verifying memory safety, edge cases, and security vulnerabilities.",
      "Omitting architectural constraints (such as SSR vs. client component boundaries or database indexing).",
    ];
  }
  if (
    cat.includes("career") ||
    cat.includes("resume") ||
    cat.includes("job-interview") ||
    cat.includes("interview")
  ) {
    return [
      "Allowing the model to fabricate achievements or metrics that you cannot defend during in-depth technical loops.",
      "Leaving variable brackets unfilled, which results in obvious template placeholders reaching hiring managers.",
      "Using passive job descriptions (e.g. 'assisted with') instead of quantified leadership actions.",
    ];
  }
  if (
    cat.includes("marketing") ||
    cat.includes("sales") ||
    cat.includes("seo") ||
    cat.includes("business") ||
    cat.includes("copywriting")
  ) {
    return [
      "Failing to define a singular, clear Call-to-Action (CTA), resulting in unfocused and diluted messaging.",
      "Accepting high-level marketing buzzwords that sound impressive but say nothing concrete to users.",
      "Not fact-checking competitive claims, legal guarantees, or pricing specifications generated by the model.",
    ];
  }
  if (
    cat.includes("writing") ||
    cat.includes("content") ||
    cat.includes("email") ||
    cat.includes("creative")
  ) {
    return [
      "Accepting the first draft without asking the AI to trim 20% of redundant filler words.",
      "Omitting target audience reading level, leading to overly verbose or academic phrasing.",
      "Ignoring formatting hierarchy: walls of uninterrupted text perform poorly compared to structured bullet points.",
    ];
  }
  return [
    "Giving minimal context and expecting nuanced, expert-level strategic output.",
    "Not validating factual references, citations, or statistical claims with verified primary sources.",
    "Skipping the customization step and pasting raw bracketed template variables into the AI chat.",
  ];
}

/**
 * Normalizes prompt with convenience properties like categoryName, template, tips, and commonMistakes
 */
function normalizePrompt(prompt: Prompt): Prompt {
  return {
    ...prompt,
    categoryName: prompt.categoryName || categoryMap.get(prompt.category) || prompt.category,
    template: prompt.template || prompt.prompt,
    tips: prompt.tips && prompt.tips.length > 0 ? prompt.tips : getDefaultTips(prompt),
    commonMistakes:
      prompt.commonMistakes && prompt.commonMistakes.length > 0
        ? prompt.commonMistakes
        : getDefaultMistakes(prompt),
  };
}

/**
 * Retrieves all prompts in the system
 */
export function getAllPrompts(): Prompt[] {
  return PROMPTS.map(normalizePrompt);
}

/**
 * Retrieves a single prompt by its unique ID (e.g. 'prompt-001')
 */
export function getPromptById(id: string): Prompt | undefined {
  const found = PROMPTS.find((p) => p.id === id);
  return found ? normalizePrompt(found) : undefined;
}

/**
 * Retrieves a single prompt by its URL slug
 */
export function getPromptBySlug(slug: string): Prompt | undefined {
  const found = PROMPTS.find((p) => p.slug === slug);
  return found ? normalizePrompt(found) : undefined;
}

/**
 * Retrieves all prompts belonging to a category
 */
export function getPromptsByCategory(categorySlug: string): Prompt[] {
  return PROMPTS.filter((p) => p.category.toLowerCase() === categorySlug.toLowerCase()).map(normalizePrompt);
}

/**
 * Retrieves all prompts compatible with a specific AI model
 */
export function getPromptsByModel(modelId: AIModelId): Prompt[] {
  return PROMPTS.filter((p) => p.compatibleModels.includes(modelId)).map(normalizePrompt);
}

/**
 * Retrieves all prompts with a specific tag
 */
export function getPromptsByTag(tag: string): Prompt[] {
  const normalizedTag = tag.toLowerCase().trim();
  return PROMPTS.filter((p) => p.tags.some((t) => t.toLowerCase() === normalizedTag)).map(normalizePrompt);
}

/**
 * Retrieves featured prompts
 */
export function getFeaturedPrompts(limit?: number): Prompt[] {
  const featured = PROMPTS.filter((p) => p.featured).map(normalizePrompt);
  return typeof limit === "number" ? featured.slice(0, limit) : featured;
}

/**
 * Retrieves trending prompts
 */
export function getTrendingPrompts(limit?: number): Prompt[] {
  const trending = PROMPTS.filter((p) => p.trending).map(normalizePrompt);
  return typeof limit === "number" ? trending.slice(0, limit) : trending;
}

/**
 * Retrieves related prompts for a given prompt ID
 */
export function getRelatedPrompts(promptId: string, limit: number = 3): Prompt[] {
  const current = getPromptById(promptId);
  if (!current) return [];

  // 1. First prioritize explicitly linked relatedPromptIds
  const explicitlyRelated = current.relatedPromptIds
    .map((id) => getPromptById(id))
    .filter((p): p is Prompt => p !== undefined);

  if (explicitlyRelated.length >= limit) {
    return explicitlyRelated.slice(0, limit);
  }

  // 2. Fall back to same category prompts excluding current
  const categoryFallback = PROMPTS.filter(
    (p) => p.category === current.category && p.id !== current.id && !current.relatedPromptIds.includes(p.id)
  ).map(normalizePrompt);

  const combined = [...explicitlyRelated, ...categoryFallback];
  return combined.slice(0, limit);
}

/**
 * Multi-facet filtering and sorting across prompts
 */
export function filterPrompts(options: PromptFilterOptions = {}): Prompt[] {
  return searchPrompts(options.search || "", options);
}

/**
 * Full-text search and multi-facet filtering across prompts
 */
export function searchPrompts(query: string = "", options: PromptFilterOptions = {}): Prompt[] {
  const q = (query || options.search || "").toLowerCase().trim();

  const filtered = PROMPTS.filter((p) => {
    // 1. Text Search matching title, shortDescription, description, tags, and category
    if (q) {
      const titleMatch = p.title.toLowerCase().includes(q);
      const shortDescMatch = p.shortDescription.toLowerCase().includes(q);
      const descMatch = p.description.toLowerCase().includes(q);
      const tagMatch = p.tags.some((t) => t.toLowerCase().includes(q));
      const catMatch = p.category.toLowerCase().includes(q);

      if (!titleMatch && !shortDescMatch && !descMatch && !tagMatch && !catMatch) {
        return false;
      }
    }

    // 2. Category Filter
    if (options.category && options.category !== "all") {
      if (p.category.toLowerCase() !== options.category.toLowerCase()) {
        return false;
      }
    }

    // 3. Difficulty Filter
    if (options.difficulty && options.difficulty !== "all") {
      if (p.difficulty !== options.difficulty) {
        return false;
      }
    }

    // 4. AI Model Filter
    if (options.model && options.model !== "all") {
      if (!p.compatibleModels.includes(options.model)) {
        return false;
      }
    }

    // 5. Tag Filter
    if (options.tag && options.tag !== "all") {
      const targetTag = options.tag.toLowerCase();
      if (!p.tags.some((t) => t.toLowerCase() === targetTag)) {
        return false;
      }
    }

    // 6. Use Case Filter
    if (options.useCase && options.useCase !== "all") {
      const targetUseCase = options.useCase.toLowerCase();
      if (!p.useCases.some((uc) => uc.toLowerCase().includes(targetUseCase))) {
        return false;
      }
    }

    // 7. Featured Filter
    if (options.featured !== undefined) {
      if (p.featured !== options.featured) {
        return false;
      }
    }

    // 8. Trending Filter
    if (options.trending !== undefined) {
      if (p.trending !== options.trending) {
        return false;
      }
    }

    return true;
  }).map(normalizePrompt);

  // Sorting
  if (options.sort) {
    filtered.sort((a, b) => {
      if (options.sort === "trending") {
        if (a.trending !== b.trending) return a.trending ? -1 : 1;
        if (a.featured !== b.featured) return a.featured ? -1 : 1;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      }
      if (options.sort === "newest") {
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      }
      if (options.sort === "title") {
        return a.title.localeCompare(b.title);
      }
      // "popular" default (or "most-copied" legacy fallback)
      if (q) {
        const scoreA = scorePrompt(a, q)?.score || 0;
        const scoreB = scorePrompt(b, q)?.score || 0;
        if (scoreA !== scoreB) return scoreB - scoreA;
      }
      if (a.featured !== b.featured) return a.featured ? -1 : 1;
      if (a.trending !== b.trending) return a.trending ? -1 : 1;
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
  } else if (q) {
    filtered.sort((a, b) => {
      const scoreA = scorePrompt(a, q)?.score || 0;
      const scoreB = scorePrompt(b, q)?.score || 0;
      return scoreB - scoreA;
    });
  }

  return filtered;
}

/**
 * Extracts all unique tags across prompts, ordered by popularity
 */
export function getAllTags(): string[] {
  const counts: Record<string, number> = {};
  PROMPTS.forEach((p) => {
    p.tags.forEach((t) => {
      const lower = t.toLowerCase();
      counts[lower] = (counts[lower] || 0) + 1;
    });
  });
  return Object.keys(counts).sort((a, b) => counts[b] - counts[a]);
}

/**
 * Extracts all unique use cases across prompts
 */
export function getAllUseCases(): string[] {
  const cases = new Set<string>();
  PROMPTS.forEach((p) => {
    p.useCases.forEach((uc) => cases.add(uc));
  });
  return Array.from(cases);
}

/**
 * Returns overall repository statistics
 */
export function getPromptStats() {
  return {
    totalPrompts: PROMPTS.length,
    totalCategories: CATEGORIES.length,
    featuredCount: PROMPTS.filter((p) => p.featured).length,
    trendingCount: PROMPTS.filter((p) => p.trending).length,
  };
}
